### PR TITLE
Replace vis-graph component with happi-graph for Asset Lineage

### PR DESCRIPTION
**Pull request by sarbull**
I created a new component called `happi-graph` which replaces and deprecates the `vis-graph` used in Asset Lineage.

It does have a new render engine using d3 library and new features such as: zoom in, zoom out, fit to screen and new node icons and new design.

*EDIT*:
This pull request also removes the http depdency on d3 which will now be included in the `package.json` via NPM dependencies, properly.

image

### CODE REVIEW

**Comment by sarbull** [comment]
Do not merge this yet.

**Comment by grahamwallis** [comment]
@sarbull Looks like a potentially good modification. One thing I wanted to check is the provenance of the happi-graph code. Is the code original to you? If not we should check the license details of the original.

**Comment by bogdan-sava** [comment]
@sarbull mark the pull request as draft in order not to be merged by mistake ( by missing your comment )

**Comment by sarbull** [comment]
> @sarbull Looks like a potentially good modification. One thing I wanted to check is the provenance of the happi-graph code. Is the code original to you? If not we should check the license details of the original.

@grahamwallis i started from a codepen d3.js html5 plain example and adapt everything to work under a polymer web component

initially here https://github.com/sarbull/happi-graph, check first commits, but then moved the implementation completely under egeria-ui for faster testing and development purposes, it's supposed to be an external generic component based on polymer, but didn't got time to deploy it under NPM Registry and add proper dependency in egeria-ui

the node content renderings and everything that's inside a node it's my work, which is on top of the initial codepen graph renderer who only displayed singular values within the directed graph nodes

**Comment by planetf1** [comment]
From https://blog.codepen.io/documentation/licensing/ it appears the examples are MIT licensed. 
Mostly this license is ok, but we should check. There may be a need to include the original license

**Comment by sarbull** [comment]
@planetf1 we will drop this initial implementation, but in another release.. there were some requirements that could not be covered by `vis-graph`, one of that requirement was to work on IE 11.. the other was the enrichment of the node graph design, some interaction with the node contents to be defined and i decided to go with the `d3` library to gain more control on what we render and how we render

`vis-graph` will be deprecated, step by step, after we stabilize the `happi-graph` component

we need more control on graph display mechanisms

**Comment by planetf1** [comment]
Agree with those thoughts...

**Comment by sarbull** [comment]
@bogdan-sava please reopen this pull-request and remove it as a draft

**Comment by sarbull** [comment]
@bogdan-sava please reopen this pull-request

**Review by bogdan-sava — APPROVED** [review]

**Pull request merged**
